# Generated by Django 4.1.2 on 2022-10-16 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Outward', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Text',
        ),
    ]
